services:
  springapp:
    build: ./product-catalog-service
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/product-catalog
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    ports:
      - "8080:8080"    

  db:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product-catalog
      - MYSQL_USER=sanchit
      - MYSQL_PASSWORD=superroot
